name: Algolia DocSearch Scraper

on:
  workflow_dispatch: 
  # push:
  #   branches:
  #     - main

jobs:
  algolia-crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .env file
        run: |
          echo "REACT_APP_ALGOLIA_API_KEY=${{ secrets.REACT_APP_ALGOLIA_API_KEY }}" >> .env
          echo "REACT_APP_ALGOLIA_APP_ID=${{ secrets.REACT_APP_ALGOLIA_APP_ID }}" >> .env
          echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> .env
          echo "REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }}" >> .env
          echo "REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}" >> .env
          echo "REACT_APP_PROJECT_NAME=${{ secrets.REACT_APP_PROJECT_NAME }}" >> .env
          echo "REACT_APP_PROJECT_OWNER=${{ secrets.REACT_APP_PROJECT_OWNER }}" >> .env
          echo "CONFIG=$(cat algolia.config.json | jq -r tostring)" >> .env

      - name: Run Algolia DocSearch Scraper (Docker)
        run: |
          docker run \
            --env-file=.env \
            -v ${{ github.workspace }}:/app \
            algolia/docsearch-scraper
